name: Build LaTeX
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: tawalaya/latex-diff-action@v1
        with:
          root_file: article.tex
          compile_diff: true
      - name: Upload compiled article
        uses: actions/upload-artifact@v2
        with:
          path: |
            article.pdf
            diff.pdf
