name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Compile Main Document
        uses: shiruken/latex-diff-action@v1
        with:
          root_file: article.tex
          compile_diff: true
      - name: Upload Compiled Main Document
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: |
            article.pdf
            diff.pdf
      - name: Compile Supplementary Document
        uses: shiruken/latex-diff-action@v1
        with:
          root_file: supplement.tex
          compile_diff: true
      - name: Upload Compiled Supplementary Document
        uses: actions/upload-artifact@v3
        with:
          name: supplement
          path: |
            supplement.pdf
            diff.pdf
            
