name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Compile LaTeX document
        uses: shiruken/latex-diff-action@v1
        with:
          root_file: article.tex
          compile_diff: true
      - name: Upload compiled article
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            article.pdf
            diff.pdf
