name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: tawalaya/latex-diff-action@v1
        with:
          root_file: article.tex
      - name: Upload compiled article
        uses: actions/upload-artifact@v3
        with:
          path: article.pdf
